import type { LogEvent } from '../../shared/api/types';

/** A minimal, entirely-empty event - every optional field null/empty ("sparse"). */
export function sparseEvent(overrides: Partial<LogEvent> = {}): LogEvent {
  return {
    timestamp: null,
    timestampRaw: null,
    schemaVersion: null,
    service: null,
    serviceSourceHint: null,
    severity: null,
    severityNumber: null,
    message: null,
    logger: null,
    thread: null,
    exception: null,
    traceId: null,
    spanId: null,
    journeyId: null,
    eventId: null,
    businessStep: null,
    uiIdentifier: null,
    errorCode: null,
    correlationId: null,
    protectedFields: { cif: null, userName: null, customerId: null, deviceId: null, deviceIp: null },
    devicePlatformType: null,
    language: null,
    serverIp: null,
    serverHost: null,
    unknownTopLevelFields: {},
    unknownMdcFields: {},
    malformed: false,
    rawLine: null,
    sourceId: null,
    composeProject: null,
    composeService: null,
    containerId: null,
    containerName: null,
    stream: null,
    namespace: null,
    pod: null,
    ...overrides,
  };
}

/** Every field populated ("full") - the event a real Docker-sourced, fully-parsed, fully-enriched log line would produce. */
export function fullEvent(overrides: Partial<LogEvent> = {}): LogEvent {
  return sparseEvent({
    timestamp: '2026-01-01T12:00:00.123Z',
    timestampRaw: '2026-01-01T12:00:00.123Z',
    schemaVersion: '1.0',
    service: 'payments-api',
    serviceSourceHint: 'payments-api-compose',
    severity: 'ERROR',
    severityNumber: 40,
    message: 'Payment authorization failed',
    logger: 'com.example.PaymentService',
    thread: 'reactor-http-nio-2',
    exception: 'java.lang.RuntimeException: timeout\n\tat com.example.PaymentService.pay(PaymentService.java:42)',
    traceId: 'trace-000100',
    spanId: 'span-000200',
    journeyId: 'journey-000300',
    eventId: 'event-000400',
    businessStep: 'AUTHORIZE_PAYMENT',
    uiIdentifier: 'checkout-submit',
    errorCode: 'ERR_TIMEOUT',
    correlationId: 'corr-000500',
    protectedFields: {
      cif: 'CIF***890',
      userName: 'jo***oe',
      customerId: 'CUST***456',
      deviceId: 'DEV***789',
      deviceIp: '10.0.***.***',
    },
    devicePlatformType: 'WEB',
    language: 'en',
    serverIp: '10.0.0.5',
    serverHost: 'gateway-1',
    unknownTopLevelFields: { extraField: 'extra-value' },
    unknownMdcFields: { 'custom.mdc.key': 'mdc-value' },
    malformed: false,
    rawLine: null,
    sourceId: 'local-docker',
    composeProject: 'log-explorer-demo',
    composeService: null,
    containerId: 'c1234567890',
    containerName: 'payments-api-1',
    stream: 'stdout',
    namespace: null,
    pod: null,
    ...overrides,
  });
}
